name: space_ai
channels:
  - defaults
  - pytorch # Add pytorch channel for PyTorch packages
dependencies:
  - python=3.11 # Versions >3.11 won't work with torchtext
  - pandas
  - jsonschema
  - pytorch=2.2.0=cpu_*
  - torchtext=0.17.0